version: '3.4'

name: fitness

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - docker_sqlserver

  docker_sqlserver:
    container_name: docker_sqlserver
    build:
      context: .
      dockerfile: API/db.Dockerfile
    ports:
      - "1433:1433"