version: '3.4'

name: fitness

services:
  api:
    container_name: api
    build:
      context: API
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - docker_sqlserver

  docker_sqlserver:
    container_name: docker_sqlserver
    build:
      context: API
      dockerfile: db.Dockerfile
    ports:
      - "1433:1433"

  angular_app:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile  
    ports:
      - "4200:4200" 